config/routes.rb
MyCat1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :doctors, except: [:destroy, :edit, :update] do
    resources :comments
  end
  resources :companies
  resources :cabinets
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :doctors
    resources :companies
  end
  get '/companies/city/:city_id',
    to: 'companies#sort_by_city', as: 'companies_city_sort'
  get '/doctors/city/:city_id',
    to: 'doctors#sort_by_city', as: 'doctors_city_sort'
  get '/cabinets/city/:city_id',
    to: 'cabinets#sort_by_city', as: 'cabinets_city_sort'
  get '/doctors/speciality/:speciality_id',
    to: 'doctors#sort_by_speciality', as: 'doctors_speciality_sort'
  get '/doctors/city/:city_id/speciality/:speciality_id',
    to: 'doctors#sort_by_both', as: 'doctors_both_sort'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contacts
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>Sample App</h1>
<div class="row">
  <div class="col-xs-12 col-md-8">.col-xs-12 col-md-8</div>
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
</div>

<!-- Columns start at 50% wide on mobile and bump up to 33.3% wide on desktop -->
<div class="row">
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
  <div class="col-xs-6 col-md-4">.col-xs-6 .col-md-4</div>
</div>

<!-- Columns are always 50% wide, on mobile and desktop -->
<div class="row">
  <div class="col-xs-6">.col-xs-6</div>
  <div class="col-xs-6">.col-xs-6</div>
</div>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Home') %>
<h1>Home page of Sample App</h1>
<p>
  This is the home page for the
  sample application.
</p>

app/views/static_pages/home.html.erb
<div class="container">
<div class="center hero-unit">
  <h1>ВРАЧИ УКРАИНЫ</h1>

  <h2>
    Здесь вы найдете любого врача и любую больницу. 
    Только здесь достоверная информация и отзывы о врачах
  </h2>

  <%= link_to "Зарегистрироваться!", signup_path, class: "btn btn-large btn-primary" %>
</div>
      <div class="row marketing">
        <div class="col-lg-6">
          <h4><%= link_to t("hospitals"), companies_path %></h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4><%= link_to t("cabinets"), cabinets_path %></h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4>Subheading</h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>

        <div class="col-lg-6">
          <h4><%= link_to "Все врачи", doctors_path %></h4>
          <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

          <h4><%= link_to "Пользователи", users_path %></h4>
          <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

          <h4><%= link_to "Admin", admin_path %></h4>
          <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
        </div>
      </div>

</div>