config/routes.rb
MyCat1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :doctors, except: [:destroy, :edit, :update] do
    resources :comments
  end
  resources :companies
  resources :cabinets
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :doctors
    resources :companies
  end
  get '/companies/city/:city_id',
    to: 'companies#sort_by_city', as: 'companies_city_sort'
  get '/doctors/city/:city_id',
    to: 'doctors#sort_by_city', as: 'doctors_city_sort'
  get '/cabinets/city/:city_id',
    to: 'cabinets#sort_by_city', as: 'cabinets_city_sort'
  get '/doctors/speciality/:speciality_id',
    to: 'doctors#sort_by_speciality', as: 'doctors_speciality_sort'
  get '/doctors/city/:city_id/speciality/:speciality_id',
    to: 'doctors#sort_by_both', as: 'doctors_both_sort'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :doctors
  has_many :company_types
  has_many :comments, as: :commentable

  belongs_to :city, counter_cache: true
  belongs_to :main_doctor, :class_name => 'Doctor'
  validates :name, presence: true, length: { maximum: 100 }
  validates :city_id, presence: true
  # scope :kolvo, ->(city_id) { where("city_id = ?", city_id) }
end

app/models/company_type.rb
class CompanyType < ActiveRecord::Base
  has_one :company
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :find_company, only: [:show, :edit, :update]
  before_action :get_cities,   only: [:index, :sort_by_city]
  add_breadcrumb "Home", :root_path
  add_breadcrumb "All companies", :companies_path

  def index
    @companies = Company.paginate(page: params[:page]).per_page(10)
    # @companies = @companies.kolvo(params[:sort_by_city]) if params[:sort_by_city]
  end

  def sort_by_city
    @companies = Company.where("city_id = ?", params[:city_id]).paginate(page: params[:page]).per_page(10)
    @city = City.find(params[:city_id])
    add_breadcrumb "#{@city.name}", "#{@city.id}"
    render 'index'
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "Company added"
      redirect_to companies_url
    else
      render 'new'
    end
  end

  def show
    @city = City.find(@company.city_id)
    add_breadcrumb "#{@city.name}", "city/#{@city.id}"
    add_breadcrumb "#{@company.name}"
  end

  def edit
  end

  def update
    if @company.update_attributes(company_params)
      flash[:success] = "Успешно обновлено"
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id]).destroy
    flash[:success] = "Company deleted"
    redirect_to companies_url
  end

  private
    def company_params
      params.require(:company).permit(:name, :desc, :adress, :contacts, 
                               :main_doctor_id, :type_company_id, :city_id)
    end

    def find_company
      @company = Company.find(params[:id])
    end

    def get_cities
      @cities = City.joins(:company).order('companies_count DESC').uniq
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_fields.html.erb
  <%= render 'shared/error_messages', object: @company %>
 
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :adress %>
  <%= f.text_field :adress %>

  <%= f.label :desc %>
  <%= f.text_field :desc %>

  <%= f.label "City:"  %>
  <%= collection_select(:company, :city_id, 
                        City.order('pop DESC'), :id, :name) %>

  <%= f.label "Глав врач:"  %>
  <%= collection_select(:company, :main_doctor_id, 
                        Doctor.order('name ASC'), :id, :name) %>

  <%= f.label :type_company_id %>
  <%= f.text_field :type_company_id %>

app/views/companies/_list.html.erb
<li>
  <%= link_to doctor.name, doctor %>
</li>

app/views/companies/edit.html.erb
<% provide(:title, 'Редактирование компании') %>
<h1>Редактирование компании</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@company) do |f| %>
       <%= render 'fields', f: f %>
      <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/companies/index.html.erb
<% provide(:title, 'All companies') %>
<h1>All companies</h1>
<div class="add-new-item">
      <span class="glyphicon glyphicon-plus"></span> 
  <%= link_to 'Добавить больницу', new_company_path %>
</div>
<%= link_to 'Все города', companies_path %> 
<% @cities.each do |city| %>
  | <%= link_to city.name, companies_city_sort_path(city.id) %>
(<%= city.companies_count %>) 
<% end %>
<p>
    <ol class="breadcrumb"><%= render_breadcrumbs %></ol>
    <%= will_paginate @companies, renderer: BootstrapPagination::Rails %>
<ul>
  <% @companies.each do |company| %>
    <li><%= link_to company.name, company %>
     | <%= link_to 'Edit', edit_company_path(company) %>
   | <%= link_to 'Delete', company, method: :delete,
     data: { confirm: "Are you sure?" } %>
  <% end %>
</ul>
    <%= will_paginate @companies, renderer: BootstrapPagination::Rails %>

app/views/companies/new.html.erb
<% provide(:title, 'Добавление компании') %>
<h1>Добавление компании</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@company) do |f| %>
       <%= render 'fields', f: f %>
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/companies/show.html.erb
<% provide(:title, @company.name) %>
<p><%= render_breadcrumbs %></p>
<div class="row">
        <h1><%= @company.name %></h1>
     <%= link_to 'Edit', edit_company_path %>
        <p>Описание: <%= @company.desc %>
        <p>Адрес: <%= @company.adress%>
        <p>Контакты: <%= @company.contacts %>
        <p>Тип компании: <%= @company.type_company_id %>
        <p>City: <%= @company.city.name %>
        <% if @company.main_doctor %>
          <p>Глав врач: <%= link_to @company.main_doctor.name, 
            @company.main_doctor %>
        <% end %>
        <% if !@company.doctors.empty? %>
          <p>Врачи:
          <%= render partial: "list", collection: @company.doctors, as: :doctor %>
        <% end %>
</div>