config/routes.rb
MyCat1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :doctors, except: [:destroy, :edit, :update] do
    resources :comments
  end
  resources :companies
  resources :cabinets
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :doctors
    resources :companies
  end
  get '/companies/city/:city_id',
    to: 'companies#sort_by_city', as: 'companies_city_sort'
  get '/doctors/city/:city_id',
    to: 'doctors#sort_by_city', as: 'doctors_city_sort'
  get '/cabinets/city/:city_id',
    to: 'cabinets#sort_by_city', as: 'cabinets_city_sort'
  get '/doctors/speciality/:speciality_id',
    to: 'doctors#sort_by_speciality', as: 'doctors_speciality_sort'
  get '/doctors/city/:city_id/speciality/:speciality_id',
    to: 'doctors#sort_by_both', as: 'doctors_both_sort'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/cabinet.rb
class Cabinet < ActiveRecord::Base
  belongs_to :company
  
  validates :name, presence: true, length: { maximum: 60 }
  validates :company_id, presence: true
  validates :city_id, presence: true
  default_scope order('name ASC')
 
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :get_all_cities,
    only: [:index, :sort_by_both, :sort_by_city, :show, :new, :edit]
  
  def index
    @cabinets = Cabinet.paginate(page: params[:page], :per_page => 9)
  end

  def sort_by_city
    @cabinets = Cabinet.where('city_id = ?', params[:city_id]).
      paginate(page: params[:page], :per_page =>10)
    @city = City.find(params[:city_id])
    add_breadcrumb "#{@city.name}", "#{@city.id}"
    render 'index'
  end

  def new
    @cabinet = Cabinet.new
  end

  def create
    @cabinet = Cabinet.new(cabinet_params)
    if @cabinet.save
      flash[:success] = "Новый кабинет успешно добавлен"
      redirect_to cabinets_url
    else
      render 'new'
    end
  end

  def show
    @cabinet = Cabinet.find(params[:id])
    @city = City.find(@cabinet.city_id)
    add_breadcrumb "#{@city.name}", "city/#{@city.id}"
    add_breadcrumb "#{@cabinet.name}"
  end
  
  def edit
  end
  
  def update
    if @cabinet.update_attributes(cabinet_params)
      flash[:success] = "Успешно обновлено"
      redirect_to @cabinet
    else
      render 'edit'
    end
  end

  def destroy
    @cabinet.destroy
    flash[:success] = "Успешно удален"
    redirect_to cabinets_url
  end
  
  private

    def cabinet_params
      params.require(:cabinet).permit(:name, :desc, :company_id, :city_id, 
                                    :adress, :shedule,)
    end

    def correct_user
      @cabinet = Cabinet.find(params[:id])
    end

    def get_all_cities
      @cities = City.joins(:cabinet).order('cabinets_count DESC').uniq
    end
    
  
end

app/helpers/cabinets_helper.rb
module CabinetsHelper
end

app/views/cabinets/_cabinet.html.erb
<li>
  <%= link_to cabinet.name, cabinet %>
  | <%= link_to "edit", edit_cabinet_path(cabinet) %>
| <%= link_to "delete", cabinet, method: :delete, 
                                data: { confirm: "Вы уверены?" } %>
</li>

app/views/cabinets/_fields.html.erb
      <%= render 'shared/error_messages', object: @cabinet %>
      <%= f.label 'Название' %>
      <%= f.text_field :name %>

      <%= f.label :desc %>
      <%= f.text_field :desc %>

      <%= f.label :adress  %>
      <%= f.text_field :adress %>

      <%= f.label "City:"  %>
      <%= collection_select(:cabinet, :city_id, City.all, :id, :name) %>

      <%= f.label "Подшефное учреждение:"  %>
      <%= collection_select(:cabinet, :company_id, Company.all, :id, :name) %>

app/views/cabinets/_leftside.html.erb
    <div class="list-group">
      <a href="<%= cabinets_path %>" class="list-group-item active">Все города</a>
          <% @cities.each do |city| %>
           <a href="<%= cabinets_city_sort_path(city.id) %>" class="list-group-item">
            <span class="badge"><%= city.cabinets_count %></span><%= city.name %></a>
            <% end %>
          </div>

app/views/cabinets/edit.html.erb
<% provide(:title, "Редактирование кабинета") %>
<h1>Редактирование кабинета</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@cabinet) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Сохранить изменения", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>

app/views/cabinets/index.html.erb
<% provide(:title, 'Частные кабинеты') %>
<div class="row">
  <div class="col-md-3">
    <%= render "leftside" %>
      </div>
  <div class="col-md-9">
    <h1>Частные кабинеты</h1>
    <div class="add-new-item">
      <span class="glyphicon glyphicon-plus"></span> 
      <%= link_to 'Новый кабинет', new_cabinet_path %>
    </div>
    <ol class="breadcrumb"><%= render_breadcrumbs %></ol>
    <%= will_paginate @cabinets, renderer: BootstrapPagination::Rails %>
    <ul class="cabinets">
    <%= render @cabinets %>
    </ul>
    <%= will_paginate @cabinets, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/cabinets/new.html.erb
<% provide(:title, 'Добавление кабинета') %>
<h1>Новый кабинет</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@cabinet) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Добавить кабинет", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/cabinets/show.html.erb
<% provide(:title, @cabinet.name) %>

<div class="row">
  <div class="col-md-3">
    <%= render "leftside" %>
      </div>
      <div class="col-md-9">
        <ol class="breadcrumb"><%= render_breadcrumbs %></ol>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @cabinet.name %></h3>
      </div>
    <div class="panel-body">
      <%= @cabinet.desc %>
      <% if @cabinet.company %>
        <p>Company: <%= link_to @cabinet.company.name, @cabinet.company %>
      <% end %>
    </div>

  </div>
</div>
</div>