config/routes.rb
MyCat1::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :doctors, except: [:destroy, :edit, :update] do
    resources :comments
  end
  resources :companies
  resources :cabinets
  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :doctors
    resources :companies
  end
  get '/companies/city/:city_id',
    to: 'companies#sort_by_city', as: 'companies_city_sort'
  get '/doctors/city/:city_id',
    to: 'doctors#sort_by_city', as: 'doctors_city_sort'
  get '/cabinets/city/:city_id',
    to: 'cabinets#sort_by_city', as: 'cabinets_city_sort'
  get '/doctors/speciality/:speciality_id',
    to: 'doctors#sort_by_speciality', as: 'doctors_speciality_sort'
  get '/doctors/city/:city_id/speciality/:speciality_id',
    to: 'doctors#sort_by_both', as: 'doctors_both_sort'
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contacts', to: 'static_pages#contacts'
  get '/signup', to: 'users#new'
  get '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">My catalog</a>
    by Dimich
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",    about_path %></li>
      <li><%= link_to "Больницы", companies_path %></li>
      <li><%= link_to "Врачи",    doctors_path %></li>
      <li><%= link_to "Contacts", contacts_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
      <%= link_to "врачи украины", root_path, id: "logo" %>
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("homepage"), root_path %></li>
        <li class="dropdown">
          <%= link_to companies_path, class: "dropdown-toggle",
            data: { toggle: "dropdown" } do %>
            <%= t('hospitals') %><b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t("hospitals"), companies_path %></li>
            <li><%= link_to t("cabinets"), cabinets_path %></li>
            <li><%= link_to t("add_hospital"), new_company_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <%= link_to doctors_path, class: "dropdown-toggle",
            data: { toggle: "dropdown" } do %>
            Врачи <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Все врачи", doctors_path %></li>
            <li><%= link_to "Добавить врача", new_doctor_path %></li>
          </ul>
        </li>  
         <% if signed_in? %>
            <li><%= link_to "Пользователи", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Мой кабинет <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Профиль", current_user %></li>
                <li><%= link_to "Найтройки", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Выйти", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Вход", signin_path %></li>
          <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>